Watching for file changes with StatReloader
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py", line 7, in get
    return render(request, 'main_page.html')
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: main_page.html
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /history/
Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py", line 22, in get
    return render(request, 'history.html')
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: history.html
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'media'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py", line 7, in get
    return render(request, 'main_page.html')
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 38: 'media', expected 'endblock'. Did you forget to register or load this tag?
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'media'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py", line 7, in get
    return render(request, 'main_page.html')
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 38: 'media', expected 'endblock'. Did you forget to register or load this tag?
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'media'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py", line 7, in get
    return render(request, 'main_page.html')
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 38: 'media', expected 'endblock'. Did you forget to register or load this tag?
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'media'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py", line 7, in get
    return render(request, 'main_page.html')
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 38: 'media', expected 'endblock'. Did you forget to register or load this tag?
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\defaulttags.py", line 1027, in find_library
    return parser.libraries[name]
KeyError: 'media'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py", line 7, in get
    return render(request, 'main_page.html')
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\defaulttags.py", line 1089, in load
    lib = find_library(parser, name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\defaulttags.py", line 1029, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'media' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /history/
Not Found: /favicon.ico
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /history/
Not Found: /history/
Not Found: /history/
Not Found: /favicon.ico
Not Found: /history/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /projects/
Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 213, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: img_carousels/img_carousel.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py", line 23, in get
    return render(request, 'projects.html')
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: img_carousels/img_carousel.html
Not Found: /favicon.ico
Internal Server Error: /projects/
Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 213, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: simple/carousel.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py", line 23, in get
    return render(request, 'projects.html')
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: simple/carousel.html
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /projects/img/prev.svg
Not Found: /projects/img/next.svg
Not Found: /projects/img/2.png
Not Found: /projects/img/1.png
Internal Server Error: /projects/
Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 213, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: simple_carousel.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py", line 23, in get
    return render(request, 'projects.html')
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: simple_carousel.html
Not Found: /favicon.ico
Internal Server Error: /projects/
Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\engine.py", line 213, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: simple_carousel.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py", line 23, in get
    return render(request, 'projects.html')
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\env\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: simple_carousel.html
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\alexm\GitHub\Awesomedreamis\dream_cv\app_cv\views.py changed, reloading.
Watching for file changes with StatReloader
